/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fcf8ff",
        "on-tertiary-fixed": "#351000",
        "outline": "#777587",
        "inverse-surface": "#302f39",
        "surface-dim": "#dcd8e5",
        "on-surface": "#1b1b24",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae6f4",
        "secondary-fixed": "#e9ddff",
        "secondary": "#6b38d4",
        "on-background": "#1b1b24",
        "secondary-fixed-dim": "#d0bcff",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#ffb695",
        "tertiary-container": "#a44100",
        "on-primary": "#ffffff",
        "tertiary": "#7e3000",
        "surface-container-low": "#f5f2ff",
        "error-container": "#ffdad6",
        "surface": "#fcf8ff",
        "primary-fixed": "#e2dfff",
        "outline-variant": "#c7c4d8",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#c3c0ff",
        "on-surface-variant": "#464555",
        "surface-variant": "#e4e1ee",
        "surface-tint": "#4d44e3",
        "on-error": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-container-highest": "#e4e1ee",
        "on-primary-container": "#dad7ff",
        "primary": "#3525cd",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0ecf9",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf8ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "primary-container": "#4f46e5",
        "tertiary-fixed": "#ffdbcc",
        "inverse-on-surface": "#f3effc",
        "secondary-container": "#8455ef",
        "on-secondary-fixed": "#23005c",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-container": "#ffd2be",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "unit-1": "4px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin": "32px",
        "unit-8": "32px",
        "base": "4px",
        "unit-4": "16px",
        "unit-2": "8px",
        "unit-6": "24px",
      },
      fontFamily: {
        "headline-xl": ["Manrope"],
        "headline-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
